input RegisterData {
    email: String!
    password: String!
    firstName: String!
    lastName: String!
}

input SignInData {
    email: String!
    password: String!
}

type Query {
    signIn(credentials: SignInData): String
}

type Mutation {
    register(data: RegisterData): String
}